# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
# Install Node
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
  ng build --prod
  displayName: 'npm install and build'

# Install Angular CLI

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'ClarkSnacks.MTS.Web'
    customCommand: 'ng install -g @angular/cli'
  displayName: NPM Install Angular CLI

# Install NPM Packages
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'ClarkSnacks.MTS.Web'
  displayName: NPM Install Packages

# build applications
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'ClarkSnacks.MTS.Web'
    customCommand: 'ng build --prod'
  displayName: NPM Build

  # copy output to build artifacts

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)/app'
  inputs:
    SourceFolder: 'dist'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/app'

    # publish build artifacts

- task: PublishBuildArtifacts@1
  inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/app'
      ArtifactName: app
      publishLocation: Container
  displayName: "Publish artifacts"


